// The share extension has its own Info.plist (generated by
// expo-share-extension), and that plugin hardcodes App Transport Security to
// only allow cleartext HTTP to `localhost`. During local development the API
// is reached over http:// at the Mac's LAN IP (EXPO_PUBLIC_API_URL, e.g.
// http://192.168.1.73:3000), which iOS ATS then blocks in the extension —
// the fetch fails and the sheet shows the generic error state. The main app
// works because its Info.plist has NSAllowsLocalNetworking; the extension's
// does not.
//
// This plugin adds NSAllowsLocalNetworking to the extension's Info.plist so
// the extension can reach the dev API over the local network. It is harmless
// in production (HTTPS needs no ATS exception). It must be listed AFTER
// "expo-share-extension" in app.json so it runs after the extension Info.plist
// is written to disk.
//
// `ios/` is gitignored / regenerated on every prebuild, so this must live as a
// config plugin rather than a hand edit.

const fs = require("fs");
const path = require("path");
const plist = require("@expo/plist");
const { withMod, IOSConfig } = require("@expo/config-plugins");

function getShareExtensionName(config) {
  return `${IOSConfig.XcodeUtils.sanitizedName(config.name)}ShareExtension`;
}

module.exports = function withShareExtensionLocalNetworking(config) {
  // The extension Info.plist is written during the iOS `infoPlist` mod phase.
  // The `finalized` mod runs strictly last (see @expo/config-plugins
  // mod-compiler precedences), so the file is guaranteed to exist on disk by
  // the time we patch it.
  return withMod(config, {
    platform: "ios",
    mod: "finalized",
    action: (config) => {
      const extensionName = getShareExtensionName(config);
      const infoPlistPath = path.join(
        config.modRequest.platformProjectRoot,
        extensionName,
        "Info.plist"
      );

      if (!fs.existsSync(infoPlistPath)) {
        console.warn(
          `[withShareExtensionLocalNetworking] ${infoPlistPath} not found — is expo-share-extension configured?`
        );
        return config;
      }

      const parsed = plist.default.parse(fs.readFileSync(infoPlistPath, "utf8"));
      parsed.NSAppTransportSecurity = {
        ...(parsed.NSAppTransportSecurity ?? {}),
        NSAllowsLocalNetworking: true,
      };
      fs.writeFileSync(infoPlistPath, plist.default.build(parsed));

      return config;
    },
  });
};
